import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Cloud from "./component/cloudhead";
import AboutMe from "./component/aboutme";
import Projects from "./component/projects";
import Nav from "./component/nav";
import CertSlideShow from "./component/certificates";
import Contact from "./component/contact";
import Skills from "./component/skills";

import { ScrollReveal } from "reveal-on-scroll-react";
import Sidebar from "./component/sidebar";

const inter = Inter({ subsets: ["latin"] });

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Mick's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Nav />
      <br />
      <br />
      <br />

      <main>
        <Cloud />
        <Sidebar />
        <ScrollReveal.div animation="slide-in-bottom" duration={2}>
          <AboutMe />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="slide-in-right">
          <Skills />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="slide-in-left">
          <Projects />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="slide-in-right">
          <CertSlideShow />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="slide-in-left">
          <Contact />
        </ScrollReveal.div>
      </main>
    </>
  );
};

export default Home;
