import Head from "next/head";
import { Inter } from "@next/font/google";
import AboutMe from "../component/aboutme";
import Projects from "../component/projects";
import CertSlideShow from "../component/certificates";
import Contact from "../component/contact";
import Skills from "../component/skills";
import Reviews from "../component/reviews";
import Footer from "../component/footer";
import Sidebar from "../component/sidebar";

const inter = Inter({ subsets: ["latin"] });

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Mick's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Nav /> */}
      <main>
        <Sidebar />
        <AboutMe />
        <Skills />
        <Projects />
        <CertSlideShow />
        {/* <Reviews /> */}
        <Contact />
        <Footer />
      </main>
    </>
  );
};

export default Home;
