import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Cloud from "../component/cloudhead";
import AboutMe from "../component/aboutme";
import Downloadbtn from "@/component/downloadbtn";
import Projects from "../component/projects";
import Nav from "../component/nav";
import CertSlideShow from "../component/certificates";
import Contact from "../component/contact";
import Skills from "../component/skills";
import Reviews from "../component/reviews";

import { ScrollReveal } from "reveal-on-scroll-react";
import Sidebar from "../component/sidebar";
import configureSession from "../middleware/session";

const inter = Inter({ subsets: ["latin"] });

const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Mick's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <br />
      <br />
      <br />
      <main>
        <ScrollReveal.div animation="fade-in" duration={4}>
          <Cloud />
        </ScrollReveal.div>
        <ScrollReveal.div animation="fade-in" duration={3}>
          <Sidebar />
        </ScrollReveal.div>
        <ScrollReveal.div animation="fade-in" duration={2}>
          <AboutMe />
        </ScrollReveal.div>
        <ScrollReveal.div duration={4}>
          <Downloadbtn />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="fade-in" duration={1.5}>
          <Skills />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="fade-in" duration={1.5}>
          <Projects />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="fade-in" duration={1.5}>
          <CertSlideShow />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="fade-in" duration={1.5}>
          <Reviews />
        </ScrollReveal.div>
        <br />
        <ScrollReveal.div animation="fade-in" duration={1.5}>
          <Contact />
        </ScrollReveal.div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps = async (context: any) => {
  await configureSession(context.req, context.res, () => {});
  return {
    props: {},
  };
};
